apiVersion: v1
kind: Service
metadata:
  name: production
spec:
  type: LoadBalancer
  selector:
    env: production
  ports:
    - name: frontend
      port: 80
      targetPort: 3000
    - name: backend
      port: 8080
      targetPort: 5000