apiVersion: v1
kind: Service
metadata:
  name: staging
spec:
  type: LoadBalancer
  selector:
    env: staging
  ports:
    - name: frontend
      port: 80
      targetPort: 80
    - name: backend
      port: 8080
      targetPort: 5000