FROM golang:1.16-alpine AS builder
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 go build -o myapp

FROM gcr.io/distroless/base-debian10
WORKDIR /app
COPY --from=builder /app/.env /app/myapp .
EXPOSE 5000
CMD ["./myapp"]